<?php

/**
 * @file
 * Contains entity_view_group_bypass.module.
 */

/**
 * https://www.drupal.org/files/issues/2018-07-18/group-add_views_filter-2981046-9.patch
 *
 */

use Drupal\views\ViewExecutable;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_view_group_bypass_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_view_group_bypass module.
    case 'help.page.entity_view_group_bypass':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entity View Group Bypass for entity view with group media') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_render().
 */
function entity_view_group_bypass_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'media' && strpos($view->current_display, 'entity_browser_') !== FALSE) {
    $user = \Drupal::currentUser();
    if (!$user->hasPermission('administer media')) {
      $group_membership_service = \Drupal::service('group.membership_loader');
      $groups = $group_membership_service->loadByUser($user);
      $group_ids = [];
      foreach ($groups as $group) {
        $group_ids[] = $group->getGroup()->id();
      }
      foreach ($view->result as $key => $value) {
        $group_id_for_media = $value->groups_field_data_group_content_field_data_id;
        if (isset($group_id_for_media) && !in_array($group_id_for_media, $group_ids)) {
          unset ($view->result[$key]);
        }
      }
    }
  }
}
