stages:

  - build
  - release
  - prisma scan
  - Non-Production Dev Deployment
  - Non-Production Stage Deployment
  - Non-Production Dev10 Deployment
  - Non-Production Stage Post Deploy
  - Non-Production Dev Post Deploy
  - Non-Production Dev10 Post Deploy
 
Build IntranetCMS Image:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container" || $CI_COMMIT_BRANCH == "stage-container-1" || $CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA

Release:
  stage: release
  tags:
    - intranetcms-dev-runner
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    # https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_copy.md
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane copy "$CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_IMAGE/intranetcms-build:latest"
    - crane copy "$CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_TAG"
  only:
    - tags

Prisma Scan:
  stage: prisma scan
  tags:
    - twistcli
  variables:
    GIT_STRATEGY: none
  script:
    - 'export PRISMA_CI_TOKEN=$(curl -kH "Content-Type: application/json" -d "{\"username\":\"$PRISMA_CI_USERNAME\", \"password\":\"$PRISMA_CI_PASSWORD\"}" https://prismacloud.epa.gov/api/v32.01/authenticate | jq -r .token)'
    - 'curl --progress-bar -L -k --header "Authorization: Bearer $PRISMA_CI_TOKEN" https://prismacloud.epa.gov/api/v1/util/twistcli > twistcli; chmod a+x twistcli;'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA
    - ./twistcli images scan --address=https://prismacloud.epa.gov --details --token=$PRISMA_CI_TOKEN $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA
  allow_failure: true
  after_script:
    # Cleanup the above space use on Runner.
    - rm -rf $CI_PROJECT_DIR


Development:
  stage: Non-Production Dev Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms.yml | kubectl apply -f - -n cms-45-dev
  environment:
    name: dev
    url:
    kubernetes:
      namespace: cms-45-dev

Development10:
  stage: Non-Production Dev10 Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms-dev10.yml | kubectl apply -f - -n cms-45-next
  environment:
    name: dev10
    url:
    kubernetes:
      namespace: cms-45-next

Stage:
  stage: Non-Production Stage Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage-container-1"'
  tags:
    - intranetcms-stg-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/cms-k8s-stg-resources:intranetcms-stage-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms-stage.yml | kubectl apply -f - -n cms-45-stage
  environment:
    name: stage
    url:
    kubernetes:
      namespace: cms-45-stage



Post Deploy:
  stage: Non-Production Stage Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage-container-1"'
  tags:
    - intranetcms-stg-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/cms-k8s-stg-resources:intranetcms-stage-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush.yml | kubectl create -f - -n cms-45-stage
  environment:
    name: stage
    url:
    kubernetes:
      namespace: cms-45-stage

Post Deploy Dev:  
  stage: Non-Production Dev Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush.yml | kubectl create -f - -n cms-45-dev
  environment:
    name: dev
    url:
    kubernetes:
      namespace: cms-45-dev

Post Deploy Dev10:
  stage: Non-Production Dev10 Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush-dev10.yml | kubectl create -f - -n cms-45-next
  environment:
    name: dev10
    url:
    kubernetes:
      namespace: cms-45-next
