stages:

  - build
  - prisma scan
  - Non-Production Dev Deployment
  - Non-Production Stage Deployment
  - Non-Production Dev10 Deployment
  - Non-Production Stage Post Deploy
  - Non-Production Dev Post Deploy
  - Non-Production Dev10 Post Deploy
  - dast

include:
  - template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: "https://stage.intranetcms-stage.aws.epa.gov/"
  DAST_AUTH_URL: "https://stage.intranetcms-stage.aws.epa.gov/user/login"
  DAST_USERNAME_FIELD: "id:edit-name"
  DAST_PASSWORD_FIELD: "id:edit-pass"
  DAST_SUBMIT_FIELD: "id:edit-submit" #"css:.btn[type='Log in']"
  DAST_USE_AJAX_SPIDER: "false"
  DAST_TARGET_AVAILABILITY_TIMEOUT: "120"
  DAST_FULL_SCAN_ENABLED: "true"
  DAST_ZAP_CLI_OPTIONS: "-config spider.maxDepth=4"
  DAST_SKIP_TARGET_CHECK: "true"

Build IntranetCMS Image:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container" || $CI_COMMIT_BRANCH == "stage-container-1" || $CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA

Prisma Scan:
  stage: prisma scan
  tags:
    - twistcli
  variables:
    GIT_STRATEGY: none
  script:
    - 'export PRISMA_CI_TOKEN=$(curl -kH "Content-Type: application/json" -d "{\"username\":\"$PRISMA_CI_USERNAME\", \"password\":\"$PRISMA_CI_PASSWORD\"}" https://prismacloud.epa.gov/api/v32.01/authenticate | jq -r .token)'
    - 'curl --progress-bar -L -k --header "Authorization: Bearer $PRISMA_CI_TOKEN" https://prismacloud.epa.gov/api/v1/util/twistcli > twistcli; chmod a+x twistcli;'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA
    - ./twistcli images scan $CI_REGISTRY_IMAGE/intranetcms-build:$CI_COMMIT_SHORT_SHA --address=https://prismacloud.epa.gov --details --token=$PRISMA_CI_TOKEN
  allow_failure: true
  after_script:
    # Cleanup the above space use on Runner.
    - rm -rf $CI_PROJECT_DIR


Development:
  stage: Non-Production Dev Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms.yml | kubectl apply -f - -n cms-45-dev
  environment:
    name: dev
    url:
    kubernetes:
      namespace: cms-45-dev

Development10:
  stage: Non-Production Dev10 Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms-dev10.yml | kubectl apply -f - -n cms-45-next
  environment:
    name: dev10
    url:
    kubernetes:
      namespace: cms-45-next

Stage:
  stage: Non-Production Stage Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage-container-1"'
  tags:
    - intranetcms-stg-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/cms-k8s-stg-resources:intranetcms-stage-k8s-agent
    - apk add gettext
    - envsubst < k8s/intranetcms-stage.yml | kubectl apply -f - -n cms-45-stage
  environment:
    name: stage
    url:
    kubernetes:
      namespace: cms-45-stage



Post Deploy:
  stage: Non-Production Stage Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage-container-1"'
  tags:
    - intranetcms-stg-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/cms-k8s-stg-resources:intranetcms-stage-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush.yml | kubectl create -f - -n cms-45-stage
  environment:
    name: stage
    url:
    kubernetes:
      namespace: cms-45-stage

Post Deploy Dev:
  stage: Non-Production Dev Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush.yml | kubectl create -f - -n cms-45-dev
  environment:
    name: dev
    url:
    kubernetes:
      namespace: cms-45-dev

Post Deploy Dev10:
  stage: Non-Production Stage Post Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-container-10"'
  tags:
    - intranetcms-dev-runner
  image: dtzar/helm-kubectl
  script:
    - kubectl config use-context intranet-cms/intracms-infra-dev:intranetcms-dev-k8s-agent
    - apk add gettext
    - envsubst < k8s/drush.yml | kubectl create -f - -n cms-45-next
  environment:
    name: dev10
    url:
    kubernetes:
      namespace: cms-45-next

dast:
  tags:
    - intranetcms-stg-runner
  when: manual
  timeout: 2d

