views.filter.epa_web_areas_users_groups:
  type: epa_web_areas_users_groups
  label: 'Content in Groups that User belongs to'
  mapping:
    users_in_group:
      type: boolean
      label: 'Users in Group'
