<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_views_query_alter().
 */
function depth_taxonomy_view_lookup_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'organizations_with_staff') {
    $root_parent_sql = <<<SQL
CASE
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 2 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN taxonomy_term_field_data_taxonomy_term__parent_1.weight
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent_2.weight
    ELSE taxonomy_term_field_data_node__field_organization.weight
END
SQL;
    $second_parent_sql = <<<SQL
CASE
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 2 THEN -1
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent_1.weight
    ELSE taxonomy_term_field_data_node__field_organization.weight
END
SQL;

    $third_parent_sql = <<<SQL

  CASE
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 2 THEN -1
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN -1
    WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
    ELSE taxonomy_term_field_data_node__field_organization.weight
END
SQL;

    $root_parent_field = $query->addField(NULL, $root_parent_sql, 'root_parent_weight');
    $second_parent_weight = $query->addField(NULL, $second_parent_sql, 'second_parent_weight');
    $third_parent_weight = $query->addField(NULL, $third_parent_sql, 'third_parent_weight');

    array_unshift($query->orderby, ['field' => $third_parent_weight, 'direction' => 'ASC']);
    array_unshift($query->orderby, ['field' => $second_parent_weight, 'direction' => 'ASC']);
    array_unshift($query->orderby, ['field' => $root_parent_field, 'direction' => 'ASC']);

  }
}