<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_views_query_alter().
 */
function depth_taxonomy_view_lookup_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'organizations_with_staff') {
    if (isset($view->args) && count($view->args) > 0) {
      $tid = $view->args[0];
      $depth = taxonomy_term_depth_get_by_tid($tid);
    } else {
      $depth = 0;
    }

    if ($depth == 0) {
      $root_parent_sql = getRootSQL();
      $second_parent_sql = getSecondParentSQL();
      $third_parent_sql = getThirdParentSQL();

      $root_parent_field = $query->addField(NULL, $root_parent_sql, 'root_parent_weight');
      $second_parent_weight = $query->addField(NULL, $second_parent_sql, 'second_parent_weight');
      $third_parent_weight = $query->addField(NULL, $third_parent_sql, 'third_parent_weight');

      array_unshift($query->orderby, ['field' => 'taxonomy_term_field_data_node__field_organization.weight', 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $third_parent_weight, 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $second_parent_weight, 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $root_parent_field, 'direction' => 'ASC']);
    } else if ($depth == 1) {
      $second_parent_sql = getSecondParentSQL();
      $third_parent_sql = getThirdParentSQL();

      $second_parent_weight = $query->addField(NULL, $second_parent_sql, 'second_parent_weight');
      $third_parent_weight = $query->addField(NULL, $third_parent_sql, 'third_parent_weight');

      array_unshift($query->orderby, ['field' => 'taxonomy_term_field_data_node__field_organization.weight', 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $third_parent_weight, 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $second_parent_weight, 'direction' => 'ASC']);
    } else if ($depth == 2) {
      $third_parent_sql = getThirdParentSQL();

      $third_parent_weight = $query->addField(NULL, $third_parent_sql, 'third_parent_weight');

      array_unshift($query->orderby, ['field' => 'taxonomy_term_field_data_node__field_organization.weight', 'direction' => 'ASC']);
      array_unshift($query->orderby, ['field' => $third_parent_weight, 'direction' => 'ASC']);
    } else if ($depth == 3) {
      array_unshift($query->orderby, ['field' => 'taxonomy_term_field_data_node__field_organization.weight', 'direction' => 'ASC']);
    }
  }
}

/**
 * @return string
 */
function getThirdParentSQL(): string {
  $third_parent_sql = "
            CASE
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN taxonomy_term_field_data_node__field_organization.weight
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
              ELSE -1
          END";
  return $third_parent_sql;
}

/**
 * @return string
 */
function getSecondParentSQL(): string {
  $second_parent_sql = "
          CASE
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 2 THEN taxonomy_term_field_data_node__field_organization.weight
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent_1.weight
              ELSE -1
          END";
  return $second_parent_sql;
}

/**
 * @return string
 */
function getRootSQL(): string {
  $root_parent_sql = "
          CASE
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 2 THEN taxonomy_term_field_data_taxonomy_term__parent.weight
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 3 THEN taxonomy_term_field_data_taxonomy_term__parent_1.weight
              WHEN taxonomy_term_field_data_node__field_organization.depth_level = 4 THEN taxonomy_term_field_data_taxonomy_term__parent_2.weight
              ELSE taxonomy_term_field_data_node__field_organization.weight
          END";
  return $root_parent_sql;
}
