ignored_config_entities:
  - 'system.menu.*'
  - system.site
  - 'webform_composite.*'
  - 'webform.*'
  - 'core.entity_view_display.node.webform.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
