# Schema for the configuration files of the Maintenance module.
maintenance.settings:
  type: config_object
  label: 'Maintenance settings'
  mapping:
    disable_email:
      type: string
      label: 'Disable Mail'
