apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranetcms
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranetcms 
       #This needs to match label on ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: intranetcms
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "backend"
      volumes:
      - name: intranetcms-storage
        persistentVolumeClaim:
          claimName: intranetcms-efs-pvc
      containers:
      - name: intranetcms
        #image: registry.epa.gov/intranet-cms/intranet-cms-infra/:$CI_COMMIT_SHORT_SHA
        image: registry.epa.gov/intranet-cms/intranet-cms-infra/intranetcms-build:1.8
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: REDEPLOY_META
          value: $CI_JOB_ID-$CI_COMMIT_SHA
        - name: WEB_HTTPS
          value: "false"
        - name: WEB_HTTPS_ONLY
          value: "false"        
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: intranetcms-storage
          mountPath: /public
      imagePullSecrets:
        - name: glcr-auth
      
---

apiVersion: v1
kind: Service
metadata:
  name: intranetcms
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: intranetcms

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: intranetcms-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  tls:
  - hosts:
    - dev.intranetcms-dev.aws.epa.gov
    secretName: tls-devsecops-shared-webapp
  rules:
    - host: dev.intranetcms-dev.aws.epa.gov
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: intranetcms
              port: 
                number: 80
