<?php

/**
 * @file
 * Contains content_migrations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_help().
 */
function content_migrations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_migrations module.
    case 'help.page.content_migrations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content migration scripts from SQL DB') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
function content_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() === 'calendar_events') {
    format_smart_date($row);
  } else if ($migration->id() === 'staff_member') {
    create_file_and_media($row);
  } else if ($migration->id() === 'all_windows_shares') {
    process_windows_shares_row($row);
  } else if ($migration->id() === 'all_windows_shares_json') {
    process_windows_shares_row($row);
  }

}

/**
 * @param Row $row
 * @throws \Drupal\Core\Entity\EntityStorageException
 * https://webx.ord.epa.gov/sites/default/files/blog/2018/03/laraphelps.jpg
 */
function process_windows_shares_row(Row $row): void {

  $owner = $row->getSourceProperty('OwnerADAccount');
  $quota_size = $row->getSourceProperty('FSRMQuotaSizeGB');
  $owner_and_size = 'N/A';
  $owner_email = $row->getSourceProperty('EmailAddress');
  if (!isset($quota_size)) {
    $quota_size = 'N/A';
  }
  if (isset($owner) && $owner != 'N/A') {
    $rawExplodedArray = explode('=', $owner, 3); // splits into 'CN', 'Last,First,OU', rest of the string
    $rawExplodedString = $rawExplodedArray[1];
    $rawNameArray = explode(',', $rawExplodedString); // splits into 'First', 'Last', rest of string
    $owner = trim($rawNameArray[0]) . ', ' . trim($rawNameArray[1]);
    $owner_and_size = $owner . ' (' . $owner_email . ') ' . ' - ' . $quota_size . 'gb';
  }
  $row->setSourceProperty('owner_name', $owner);
  $row->setSourceProperty('owner_and_size', $owner_and_size);
  $row->setSourceProperty('owner_email', $owner_email);
}

/**
 * @param Row $row
 * @throws \Drupal\Core\Entity\EntityStorageException
 * https://webx.ord.epa.gov/sites/default/files/blog/2018/03/laraphelps.jpg
 */
function create_file_and_media(Row $row): void {
  $image_data = $row->getSourceProperty('field_staff_image');
  if (isset($image_data) && isset($image_data[0]) && !empty($image_data[0])) {
    $uri_array = explode("/", $image_data[0]['uri']);
    $file_name = $uri_array[count($uri_array) - 1];
    $file_location = str_replace("public://", "https://webx.ord.epa.gov/sites/default/files/", $image_data[0]['uri']);
    $file_data = file_get_contents($file_location);
    if ($file_data) {
      $file = file_save_data($file_data, 'public://staff/' . $file_name, FILE_EXISTS_REPLACE);
      $media = Media::create([
          'bundle' => 'image',
          'uid' => \Drupal::currentUser()->id(),
          'langcode' => \Drupal::languageManager()->getDefaultLanguage()->getId(),
          'status' => 1,
          'name' => $file_name,
          'field_media_in_library' => [
            0
          ],
          'image' => [
            'target_id' => $file->id(),
          ]
        ]
      );
      $media->save();
      $row->setSourceProperty('media_image_target_id', $media->id());
    }
  }
}

/**
 * @param Row $row
 * @throws Exception
 */
function format_smart_date(Row $row): void {
  $smart_date_field = [];
  $date = $row->getSourceProperty('field_event_date')[0];
  $start_time = strtotime($date['value']);
  $end_time = strtotime($date['value2']);
  $duration = $end_time - $start_time;
  $smart_date_field['value'] = $start_time;
  $smart_date_field['end_value'] = $end_time;
  $smart_date_field['duration'] = $duration;
  $row->setSourceProperty('field_event_date', $smart_date_field);
}
