<?php

/**
 * @file
 * Contains content_migrations.module.
 */

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_migrations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_migrations module.
    case 'help.page.content_migrations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content migration scripts from SQL DB') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
function content_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() === 'calendar_events') {
    $smart_date_field = [];
    $date = $row->getSourceProperty('field_event_date')[0];
    $start_time = strtotime($date['value']);
    $end_time = strtotime($date['value2']);
    $duration = $end_time - $start_time;
    $smart_date_field['value'] = $start_time;
    $smart_date_field['end_value'] = $end_time;
    $smart_date_field['duration'] = $duration;
    $row->setSourceProperty('field_event_date', $smart_date_field);
  }
}

