DC_PROJECT: '10351'
CIN_PROJECT: '10350'
RTP_PROJECT: '10352'
BASE_URL: 'https://jira.ord.epa.gov'
REST_URL: 'https://jira.ord.epa.gov/rest/api/2'
CREATE_ISSUE_URL: 'https://jira.ord.epa.gov/rest/api/2/issue/'
USERNAME: travel-forms
SERVER: ''
SUBMIT_MESSAGE: ''
OPTIONS: ''
DOMESTIC_PROJECT: '11533'
INTERNATIONAL_PROJECT: '11534'
VOUCHERS_PROJECT: '11630'
REGION8_PROJECT: '10731'
REGION9_PROJECT: '11431'