allow:
  default_login: true
  set_drupal_pwd: true
  default_login_roles:
    authenticated: authenticated
    webform: webform
    administrator: administrator
  default_login_users: ''
logout_goto_url: ''
activate: true
auth_source: default-sp
login_link_display_name: 'Enterprise/PIV Login'
login_link_show: true
debug: false
secure: true
httponly: false
register_users: true
header_no_cache: false
unique_id: uid
user_name: uid
sync:
  user_name: true
  mail: true
mail_attr: mail
role:
  population: ''
  eval_every_time: false
autoenablesaml: false
