checkbox_fields: customfield_10411|customfield_10415|customfield_10150|customfield_10149|customfield_10148|customfield_10151|customfield_10278|customfield_10280|customfield_11929|customfield_11930|customfield_10103
flying_out_the_country: customfield_11826
form_to_jira_mapping: |-
  {
    "your_information": {
      "your_name": "customfield_10090",
      "your_email": "customfield_10092",
      "your_phone": "customfield_10091"
    },
    "verify_your_name": "customfield_10493",
    "your_office_center": "customfield_10093",
    "ccte_division_traveler": "customfield_10501",
    "cemm_division_traveler": "customfield_10501",
    "ceser_division_traveler": "customfield_10501",
    "cphea_division_traveler": "customfield_10501",
    "orm_division_traveker": "customfield_10501",
    "osape_division_traveler": "customfield_10501",
    "osim_division_traveler": "customfield_10501",
    "ccte_divisions": "customfield_10501",
    "cemm_divisions": "customfield_10501",
    "ceser_divisions": "customfield_10501",
    "cphea_divisions": "customfield_10501",
    "orm_division": "customfield_10501",
    "osape_division": "customfield_10501",
    "osim_division": "customfield_10501",
    "traveler_information": {
      "traveler_name": "customfield_10331",
      "traveler_email": "customfield_10620",
      "traveler_phone": "customfield_11423"
    },
    "traveler_s_information": {
      "traveler_name": "customfield_10331",
      "traveler_email": "customfield_10620",
      "traveler_phone": "customfield_11423"
    },
    "verify_traveler_s_name": "customfield_10493",
    "traveler_s_office_center": "customfield_10093",
    "office_point_of_contact": "customfield_10340",
    "traveler_type": "customfield_10190",
    "travel_type": "customfield_10191",
    "passport_expiration_date": "customfield_10492",
    "emergency_contact_information": "customfield_10356",
    "traveler_s_grade": "customfield_11821",
    "title_position": "customfield_11822",
    "is_personal_annual_leave_being_requested_": "customfield_10098",
    "dates_of_approved_leave": "customfield_10099",
    "do_you_already_have_a_room_reserved_": "customfield_10112",
    "mode_s_of_transportation": "customfield_10103",
    "have_you_made_your_own_airline_reservation_": "customfield_10435",
    "would_you_like_to_request_a_specific_flight_": "",
    "information_about_specific_flight": "customfield_11927",
    "additional_information_transportation": "customfield_10111",
    "travel_purpose": "customfield_10922",
    "is_this_travel_for_an_epa_conference_": "customfield_10426",
    "please_provide_the_conference_code": "customfield_10921",
    "travel_description": "customfield_10094",
    "how_will_this_trip_benefit_the_epa_": "customfield_10198",
    "has_the_traveler_taken_hstos_training_": "customfield_11827",
    "who_is_your_deputy_ethics_official_": "customfield_11823",
    "sponsoring_organization": "customfield_11825",
    "division_director_and_or_branch_chief_s_name": "customfield_10430",
    "traveler_s_qualifications": "customfield_10195",
    "destination_country_contact_s_name": "customfield_10357",
    "destination_country_contact_s_telephone": "customfield_10357",
    "destination_country_contact_s_org": "customfield_10357",
    "hosting_organization_point_of_contact": "customfield_10357",
    "is_someone_else_paying_for_a_portion_or_all_of_the_travel_": "customfield_10199",
    "who_is_paying_": "customfield_10200",
    "epa_office_paying": "customfield_11425",
    "cross_funding_label_": "customfield_10491",
    "agency_name": "customfield_11426",
    "name_of_funding_organization": "customfield_11427",
    "has_an_ethics_form_been_prepared_": "customfield_11428",
    "has_an_ethics_form_been_approved_": "customfield_10193",
    "will_training_dollars_be_used_for_this_travel_": "customfield_10246",
    "are_others_from_your_l_c_o_attending_this_meeting_as_well_": "customfield_10431",
    "please_provide_the_names_of_the_others_attending_this_meeting_wi": "customfield_10432",
    "transportation_expenses": "customfield_10278",
    "cost_of_taxi_uber_lyft": "customfield_10413",
    "cost_of_metro_bus_public_transportation": "customfield_10414",
    "cost_of_pov": "customfield_11431",
    "cost_of_rental_car_fee": "customfield_10384",
    "cost_of_rental_car_fuel": "customfield_10385",
    "cost_of_tolls": "customfield_10387",
    "cost_of_rail": "customfield_10383",
    "additional_expenses": "customfield_10415",
    "cost_of_hotel": "customfield_10375",
    "cost_of_internet_fees": "customfield_10377",
    "cost_of_phone_calls": "customfield_10416",
    "cost_of_airport_parking": "customfield_10412",
    "cost_of_baggage_fees": "customfield_10419",
    "cost_of_atm_fees": "customfield_10418",
    "cost_of_supplies": "customfield_10417",
    "cost_of_other_expenses": "customfield_10380",
    "cost_of_conference_registration_fee": "customfield_11924",
    "cost_of_hotel_parking": "customfield_11925",
    "additional_info_text": "customfield_10141",
    "additional_information_textarea": "customfield_10141",
    "cost_of_cash_withdraw_finance_fees": "customfield_10373",
    "attachment_s_": "file",
    "travel_request_number": "customfield_10208",
    "destination": "customfield_10303",
    "departure_date": "customfield_10095",
    "requested_change": "customfield_10209",
    "please_state_your_requested_concur_update_": "customfield_10209",
    "explanation": "customfield_10290",
    "please_enter_your_date_of_birth": "customfield_11429",
    "please_enter_the_traveler_s_date_of_birth": "customfield_11429",
    "emergency_contact_information_new": "customfield_11430",
    "preferred_home_airport_new": {
      "multi": true,
      "preferred_home_airport_new": "customfield_10266"
    },
    "smoking_preference": "customfield_10120",
    "any_additional_requests_": "customfield_10291",
    "bed_size_preference": "customfield_10262",
    "hotel_preference": {
        "hotel_name": "customfield_10273",
        "account_information": "customfield_12020"
     },
    "flight_seating_preference": "customfield_10263",
    "please_state_you_question_or_comment_in_the_filed_below_": "customfield_10390",
    "comments_on_travel_experience": "customfield_10308",
    "were_all_meals_provided_through_your_registration_costs_or_by_th": "customfield_10151",
    "do_you_have_any_other_expense_you_would_like_to_reimburse_to_you": "customfield_11420",
    "return_date": "customfield_10096",
    "returning_time": "customfield_10342",
    "departing_date": "customfield_10095",
    "departing_time": "customfield_10343",
    "round_trip_flight": {
      "flying_from": "customfield_10104",
      "flying_to": "customfield_10105",
      "departing_date": "customfield_10095",
      "departing_time": "customfield_10343",
      "returning_date": "customfield_10096",
      "returning_time": "customfield_10342",
      "comments": "customfield_11952"
    },
    "one_way_flight": {
      "flying_from": "customfield_10104",
      "flying_to": "customfield_10105",
      "departing_date": "customfield_10095",
      "departing_time": "customfield_10343",
      "returning_date": "customfield_10096",
      "returning_time": "customfield_10342",
      "comments": "customfield_11952"
    },
    "multi_city_flight": "customfield_11921",
    "reservation_information": {
      "multi_fieldset": true,
      "hotel_name": "customfield_10281",
      "hotel_location": "customfield_11950",
      "hotel_phone": "customfield_11951",
      "room_rate": "customfield_10370"
    },
    "please_provide_more_information_about_the_current_status_of_the_": "customfield_11949",
    "provided_meals": "customfield_11920",
    "airline_preference": {
        "airline_name": "customfield_12021",
        "account_number": "customfield_12022"
    },
    "trip_type": "customfield_11922",
    "please_stay_within_allowable_per_diem_if_selected_rate_is_over_p": "customfield_11923",
    "address_of_meeting_s_": "customfield_11928",
    "transportation_expenses_rr": "customfield_11929",
    "additional_expenses_rr": "customfield_11930",
    "cost_of_taxi_uber_lyft_rr": "customfield_11931",
    "cost_of_metro_bus_public_transportation_rr": "customfield_11932",
    "cost_of_pov_rr": "customfield_11933",
    "cost_of_rental_car_fee_rr": "customfield_11934",
    "cost_of_rental_car_fuel_rr": "customfield_11935",
    "cost_of_tolls_rr": "customfield_11936",
    "cost_of_rail_rr": "customfield_11937",
    "cost_of_conference_registration_fee_rr": "customfield_11938",
    "cost_of_hotel_rr": "customfield_11939",
    "cost_of_hotel_parking_rr": "customfield_11940",
    "cost_of_internet_fees_rr": "customfield_11941",
    "cost_of_phone_calls_rr": "customfield_11942",
    "cost_of_airport_parking_rr": "customfield_11943",
    "cost_of_baggage_fees_rr": "customfield_11944",
    "cost_of_cash_withdraw_finance_fees_rr": "customfield_11945",
    "cost_of_atm_fees_rr": "customfield_11946",
    "cost_of_supplies_rr": "customfield_11947",
    "cost_of_other_expenses_rr": "customfield_11948",
    "epa_office_division_branch": "customfield_10330",
    "traveler_division": "customfield_11520",
    "your_division": "customfield_11520",
    "region_8_traveler_division": "customfield_10820",
    "region_8_your_division": "customfield_10820",
    "region_travel_description": "customfield_10920",
    "rental_car_size_preference": "customfield_10269",
    "rental_car_company": "customfield_10271",
    "frequent_rental_car_account_number": "customfield_10272",
    "region_returned_to": "customfield_10304",
    "region_departed_from": "customfield_10297",
    "traveler_destination": "customfield_10303",
    "approximate_return_time": "customfield_10342",
    "approximate_departure_time": "customfield_10343",
    "travel_card_paid_off": "customfield_11020",
    "site_specific_details": "customfield_10822",
    "alternative_phone": "customfield_10353",
    "name_of_room_block": "customfield_10119",
    "cost_of_airfare": "customfield_10436",
    "name_of_airline": "customfield_10438",
    "flight_number_s_": "customfield_10439",
    "has_registration_fee_been_paid_by_gov_t_purchase_card_bank_card_": "customfield_10428",
    "what_s_the_dollar_amount_to_include_in_ta": "customfield_10429",
    "departing_from": "customfield_10925",
    "returning_to": "customfield_10304",
    "pov_mileage": "customfield_10381",
    "what_day_s_are_you_presenting_": "customfield_10425",
    "transportation_to_and_from_airport": "customfield_10410",
    "site_specific_travel": "customfield_10821",
    "is_there_a_registration_fee_": "customfield_10427",
    "are_you_presenting_": "customfield_10424",
    "government_vehicle_available": "customfield_10924",
    "destination_country_contact_name_phone_organization_": "customfield_10357",
    "new_employee_": "customfield_10277",
    "what_program_s_the_trip_is_related_to_": "customfield_11521",
    "date_training_was_completed": "customfield_12520",
    "receipts": "file",
    "required_receipts": "file",
    "daily_itinerary": "file",
    "please_attach_the_approved_sf_182": "file",
    "please_attach_approved_ethics_form_": "file",
    "please_attach_your_invitational_letter_": "file",
    "reimb_or_in_kind_travel_": "customfield_10140",
    "hstos_ct_401_certificate_of_training": "file",
    "destination_country_contact_s_title": "customfield_12620",
    "destination_country_contact_s_email_address": "customfield_12621",
    "traveler_s_division_director_s_name": "customfield_12622",
    "traveler_s_center_office_deputy_director_s_name": "customfield_12623"
  }
dropdown_fields: customfield_10093|customfield_10098|customfield_10112|customfield_10120|customfield_10140|customfield_10190|customfield_10191|customfield_10193|customfield_10199|customfield_10246|customfield_10262|customfield_10263|customfield_10269|customfield_10277|customfield_10294|customfield_10297|customfield_10302|customfield_10304|customfield_10315|customfield_10316|customfield_10318|customfield_10320|customfield_10322|customfield_10324|customfield_10423|customfield_10424|customfield_10426|customfield_10427|customfield_10428|customfield_10431|customfield_10435|customfield_10501|customfield_10922|customfield_11424|customfield_11428|customfield_11826|customfield_11827|customfield_11520|customfield_10820|customfield_11922|customfield_11020|customfield_10821|customfield_10924|customfield_10925